version: '3.8'

services:
  bot:
    build: ./bot
    network_mode: host
    volumes:
      - /tmp:/tmp
    environment:
      - TZ=Europe/Moscow
      - API_TOKEN=${API_TOKEN}
      - HP_EMAIL=${HP_EMAIL}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}